### ISSUE TITLE
GoogleMapsFlutter 1.0 not suported

### ISSUE THREAD

**Issue by fvisticot** [bpillon/google_maps_cluster_manager#13]
When I try to update google_maps_flutter plugin, I get the following error:

Because no versions of google_maps_cluster_manager match >0.1.0 <0.2.0 and google_maps_cluster_manager 0.1.0 depends on google_maps_flutter ^0.5.22, google_maps_cluster_manager ^0.1.0 requires google_maps_flutter ^0.5.22.

Can you please update this plugin ?

**Comment by JayPerfetto** [comment]
+1, this is a great clustering package deserving of supporting 1.0 google maps

**Comment by bpillon** [comment]
Merged on master !
