### ISSUE TITLE
Support for latest google maps

### ISSUE THREAD

**Issue by maheshmnj** [bpillon/google_maps_cluster_manager#15]
the google maps flutter plugin has been updated to [1.0.2](https://pub.dev/packages/google_maps_flutter/changelog)
In order to use this plugin in a flutter project which uses the latest google maps,this plugin must update the google maps version it uses.
I would be glad to take up this issue if someone could guide me on what changes needs to be made.

**Comment by bpillon** [comment]
Hello. It's done since last week !

**Comment by maheshmnj** [comment]
Awesome Thanks
