### ISSUE TITLE
Overlapping clusters at lower zoom levels...

### ISSUE THREAD

**Issue by mistyn8** [bpillon/google_maps_cluster_manager#17]
How can I avoid clusters overlapping? (I need clustering for my clusters :-) ) 

I've had a look at setting levels, but can't quite understand what levels are actually doing and whatever I do seems to make it worse, not better.
Any pointers greatly received. 

![screen](https://user-images.githubusercontent.com/12418214/98151258-cb1e0700-1ec7-11eb-8d0c-c8124fe5bc0f.png)

**Comment by mistyn8** [comment]
Had another look and got a better setup with levels: [1, 4.25, 6.75, 8.25, 11.5, 14.5, 16.0, 16.5, 20.0],
rather than the default levels: [1, 3.5, 5, 8.25, 11.5, 14.5, 16.0, 16.5, 20.0],

Also have a better understanding of levels.. which basically work alongside geohash and matching substring of chars.

I think some of the issue here is that geohash inherently limits proximity due to 12chars when encoded...

#   km      
1   ± 2500
2   ± 630
3   ± 78
4   ± 20
5   ± 2.4
6   ± 0.61
7   ± 0.076
8   ± 0.019
9   ± 0.0024
10  ± 0.00060
11  ± 0.000074

So a little arbitrary when trying to match to zoom levels?

**Comment by bpillon** [comment]
Hello Mike. Indeed the values I use as default are completely arbitrary and based on few tests. Is the rendering OK now with your new values ? May be I could update the default ones with yours.

**Comment by mistyn8** [comment]
feel free, seems to work better for our needs.

FYI some user testing feedback for you
I am having to explain why the difference from the previous incarnation which was based on Fluster.
Geohash seems much more performant, but some users are a little unnerved by the clustering changing when panning viewport, as opposed to fluster where clusters remain constant when panning.

**Comment by bpillon** [comment]
I have trouble understanding exactly what you mean by "panning" ? You have a use-case where your map view size is changing ?

**Comment by mistyn8** [comment]
panning the map around (dragging without zoom)
