### ISSUE TITLE
create different markers icon

### ISSUE THREAD

**Issue by mashegoindustries** [bpillon/google_maps_cluster_manager#18]
I have 4 different types of markers that I need to show on the map.

I am aware that I can create different markers icon, depending on the isMultiple property,

This means that a marker can be multiple or single. (This means maximum 2 marker icons)

My question is,
How can I create multiple marker icons for single clusters?

Should I rather create 4 instances of cluster managers?

Something like this
policeClusterManager = _initClusterManagerPolice();
carsClusterManager = _initClusterManagerCars();
accidentClusterManager = _initClusterManagerAccident();
storeClusterManager = _initClusterManagerstore();

**Comment by bpillon** [comment]
Hello,
You can pass an item to a ClusterItem so you are able to create different icons depending on the item the ClusterItem contains.
