### ISSUE TITLE
isCluster: true or false

### ISSUE THREAD

**Issue by mashegoindustries** [bpillon/google_maps_cluster_manager#19]
Can you add some thing like isCluster: true or false.

Sometime I don't want certain map markers to cluster

Where by that particular marker wont ever cluster.

I have a situation were by a user current location is on the map,
But soon as the user moves close enough to another marker, then that user marker will cluster. 

Resulting in user not seeing their marker on the map anymore

**Comment by bpillon** [comment]
Hello.

May be you could just don't add the items you dont want to be clustered to ClusterManager and add them as markers on your own ?

**Comment by mashegoindustries** [comment]
I tried to exclude item from ClusterManager, I directly added it to the map as a marker, 

But soon as I zoom out, the marker seems to disappear

**Comment by bpillon** [comment]
Indeed, because clustered markers are updated when you zoom out. So you have to add your non clustered markers each time clustered ones are updated.

**Comment by mashegoindustries** [comment]
Noted. Closing this one
