### ISSUE TITLE
Lag when number of markers increases

### ISSUE THREAD

**Issue by SuMitVayuz** [bpillon/google_maps_cluster_manager#22]
As the number of markers increases the map begins to lag and unresponsive. And finally, the app crashes.

/// my map
GoogleMap(
                mapToolbarEnabled: false,
                zoomControlsEnabled: false,
                onMapCreated: _onMapCreated,
                myLocationEnabled: false,
                myLocationButtonEnabled: false,
                minMaxZoomPreference: MinMaxZoomPreference(1.0, 14.0),
                initialCameraPosition: CameraPosition(
                  target: widget.initialPosition,
                  zoom: _defaultZoom,
                ),
                markers: _updateMarker(
                    Provider.of<NewHomeBloc>(context).userDetailsList),
                onCameraMove: _onCameraMove,
                onCameraIdle: _onCameraIdle,
              ),

/// update marker 
 Set<Marker> _updateMarker(List<UserDetails> userDetailsList) {
    _manager.setItems(<ClusterItem<Place>>[
      for (UserDetails userDetails in userDetailsList)
        ClusterItem<Place>(LatLng(userDetails.lat, userDetails.long),
            item: Place(name: userDetails.name))
    ]);
    _manager.updateMap();
    return _markers;
  }

/// cluster manager
ClusterManager _initClusterManager() {
    return ClusterManager<Place>(items, _updateMarkers,
        markerBuilder: _markerBuilder, initialZoom: _defaultZoom);
  }
List<ClusterItem<Place>> items = [];

Not able to figure out what's causing the issue, can it be the package issue or flutter issue? Any help will be appreciated.

**Comment by bpillon** [comment]
I think you may not be using the library correctly, the _updateMarkers method is therefore called too many times, causing the application to crash.  Currently, in your `updateMarker` method you're using `setItems`method, which itself calls the `updateMarker` etc... The `updateMarker` is only here to change the state of the `items` variable (and may be do other things). And why do you set both the Google Map markers AND the Cluster Manager items ?

**Comment by SuMitVayuz** [comment]
The app was crashing when there were about 500-600 markers. Anyway, I think the issue was calling updateMarkers too many times. One more mistake was that updateMarker was called in _onCameraMove. After doing a bit of refactoring, now it is working fine.
