### ISSUE TITLE
Requesting web support

### ISSUE THREAD

**Issue by liubrandon** [bpillon/google_maps_cluster_manager#23]
Would love to see Flutter web support for marker clustering with google maps!

**Comment by bpillon** [comment]
Hello. I was planning to take a look at google_maps_flutter_web to be able to do this. I'll try to implement it asap.

**Comment by sperochon** [comment]
Hello, is there any news about this? Thanks.

**Comment by liubrandon** [comment]
I see this! https://github.com/bpillon/google_maps_cluster_manager

**Comment by bpillon** [comment]
Done !
