### ISSUE TITLE
 Moving clusters at lower zoom levels

### ISSUE THREAD

**Issue by aminethitah** [bpillon/google_maps_cluster_manager#24]
By zooming to a lower level, the clusters move from their exact positions.
![2](https://user-images.githubusercontent.com/24639703/107158293-720fb480-6989-11eb-895f-d9e588a45e85.png)
![3](https://user-images.githubusercontent.com/24639703/107158306-78059580-6989-11eb-8903-ff53461d1b43.png)

**Comment by bpillon** [comment]
Hello. You should be able to correct this by adjusting the `levels` values.

**Comment by aminethitah** [comment]
I want the clusters to stay on the exact location whene zooming down

**Comment by bpillon** [comment]
Due to the operation of geohash, it seems to be non-trivial. I may be able to find a solution in the future.
