### ISSUE TITLE
Syntax question about markerBuilder

### ISSUE THREAD

**Issue by maxouille** [bpillon/google_maps_cluster_manager#25]
Hi, 

First of all, awesome plugin, thank you ! 

I managed to make it work but I don't understand the following syntax : 
`static Future<Marker> Function(Cluster) get markerBuilder => (cluster) async `

I search on Dart documentation, stackoverflow for answers but could find a thing. Could you please explain me the getter syntax, especially why does it returns `Future<Marker> Function(Cluster)` and what does it means ? 

Best

**Comment by bpillon** [comment]
Hello Maxouille. MarkerBuilder expects a Function that takes a Cluster object in parameter and return a Future<Marker>. 
This syntax could be close to a method with ```Future<Marker> getMarker(Cluster cluster) {...}``` as signature.

**Comment by maxouille** [comment]
Thanks so the `Function()` keyword on the getter is only there to tell that the getter takes a cluster as parameter if I'm correct ?

**Comment by bpillon** [comment]
Yes. It tells that the getter returns a function which takes a `Cluster` as parameter a return a `Future<Marker>`.

**Comment by maxouille** [comment]
Thx, i close the issue :)
