### ISSUE TITLE
Zoom levels

### ISSUE THREAD

**Issue by mike-robinson** [bpillon/google_maps_cluster_manager#29]
I am trying to cluster such that when zoomed out all the way, I can get totals by country. However, what I find it when zoomed out completely the zoom level is only 2.069159507751465. So clusters from the eastern USA are still separate from the western USA. 

I get the current zoom level by listening to onCameraMove and getting the zoom level from the camera position. I can verify that the zoom range is between 2.069159507751465 and 21.0.

Any ideas of why the zoom won't go to 1.0 when fully zoomed out?

![Simulator Screen Shot - iPhone 12 Pro Max - 2021-07-22 at 13 59 03](https://user-images.githubusercontent.com/1975212/126708768-7adee556-ab19-419e-bc44-4bc2c5d788d4.png)

**Comment by bpillon** [comment]
Hello. This issue is related to Google maps, not this library. Sorry I can't help you more.
