### ISSUE TITLE
Is it available to create multiple cluster managers! 

### ISSUE THREAD

**Issue by MahmoudAbunaji** [bpillon/google_maps_cluster_manager#30]
Thank  you for useful library,  

Is it available to create multiple cluster managers and set different markers to each manager? 
If available what about handling the (onCameraMove & onCameraIdle) ?

**Comment by bpillon** [comment]
I haven't tried this yet. For the `onCameraMove` and `onCameraIdle`, I guess you just have to declare an intermediate method which calls each manager needed method.

**Comment by bpillon** [comment]
Hello. There is now an example for using multiple managers on the same map. See `multiple.dart`
