### ISSUE TITLE
possibility to exclude from clustering in certain zoom value

### ISSUE THREAD

**Issue by Marek00Malik** [bpillon/google_maps_cluster_manager#4]
So I have this case that my markers are almost at the same location (they are in the same building). 
And if I would turn off clustering they would be placed very close to each other but now one on another (tested this on zoom levels 19+), but when clustering the makers I'm not able to show them. 

Is there any possibility to add such an option that for x number of items you would not cluster them above a given zoom value one would see all items?

**Comment by bpillon** [comment]
Available in 0.2.0 version
