### ISSUE TITLE
UnCluster markers when zoomed

### ISSUE THREAD

**Issue by theshivamlko** [bpillon/google_maps_cluster_manager#49]
- When user click on Clustered marker, the markers at that spot should Unflustered and camera should zoom to it and when zoomed out the cluster should again appear.
OpenStreetMap has this feature
How to do this?
![Screenshot_20221130-151944](https://user-images.githubusercontent.com/15983730/204764239-35633dc3-2f08-41bd-8c4c-d281ed38976d.jpg)

**Comment by abhlabs** [comment]
Disclaimer:  I only started looking at this package an hour or two ago, but here's what I think would work:  write an onTap handler for the markers, then zoom the google map to a zoom level of your choice, but make sure the zoom level is at least as high as the stopClusteringZoom.

**Comment by hansvn** [comment]
@theshivamlko Check this comment: [#52 (comment)](https://github.com/bpillon/google_maps_cluster_manager/issues/52#issuecomment-1500915407)
