### ISSUE TITLE
Define custom method to define MarkerId

### ISSUE THREAD

**Issue by fvisticot** [bpillon/google_maps_cluster_manager#5]
I need to use the `mapController.showMarkerInfoWindow(MarkerId(selectedMarker.getId()));`
My pb is that the function used to set MarkerId in the cluster manager is private.
It would be nice to define our own method to define the markerId and use the same function to open the Info window.

**Comment by bpillon** [comment]
Hello @fvisticot.
You are already able to define custom MarkerId, the simplest method I see to do it is to subclass Cluster and override getId() method. Or you can just make a custom `Future<Marker> Function(Cluster<T>) markerBuilder` method.
