### ISSUE TITLE
Questions regarding markers

### ISSUE THREAD

**Issue by JihooDev** [bpillon/google_maps_cluster_manager#73]
Thank you for creating such a useful service. I have two questions. First, if there are 4,000 markers, should the server be called to add markers as the user moves the map, or should all 4,000 markers be added at once? I am curious about the performance differences between these two approaches. Second, I wonder if it is possible to change the markers to specific images. I understand that currently, markers are drawn using shapes, but can this also be customized?

**Comment by abhlabs** [comment]
My app adds 1000 markers when the map loads, and there is a very brief delay (maybe 1/4 of a second).  I think you'll need to test your situation to see if any observed delay will present a problem for your users.

Marker icons can be customized, but that has nothing to do with the google_maps_cluster_manager.   Search for "flutter google maps custom marker images" and you'll find numerous references / sample code.
