### ISSUE TITLE
[Question] Zoom / Unzoom: Cluster / non cluster

### ISSUE THREAD

**Issue by fvisticot** [bpillon/google_maps_cluster_manager#8]
I have attached a video to show my pb.
I have a cluster of 2 points
If I zoom the Cluster is broken in 2 points
BUT the 2 points are not displayed on the map (are out of the current map view)
I need to zoom out to see the 2 points coming from the cluster
What need to be done to avoid this ?

Code:

`return ClusterManager<_HistoryLocationInfo>(
      items,
      _updateMarkers,
      markerBuilder: _markerBuilder,
      extraPercent: 0.3,
      levels: [1, 3.5, 5, 8.25, 11.5, 14.5, 16, 16.5, 20],
    );`

![RPReplay_Final1594719365](https://user-images.githubusercontent.com/153679/87414836-a0ccd480-c5cc-11ea-8416-1f2cb3ecaf45.gif)

**Comment by bpillon** [comment]
Hello.
May be your marker builder has problem with not clustered markers ?
